In [4]:
import pandas as pd
import math
import numpy as np

import heapq
import numba as nb
from scipy.stats.mstats import gmean, hmean
# from state import*
from new_verrsion_print import*

# data_full = pd.read_csv('data_test.csv')
# data_full = data_full.sort_values(by=['TIME', 'PROFIT'], ascending=[False, False], ignore_index=True)
# all_fomula = np.array(pd.read_csv('congthuc.csv')['fomula'])

data_full

c:\Users\Admin\Desktop\SYSTEM\RL_INVEST\new_verrsion_print.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[1] = 1
c:\Users\Admin\Desktop\SYSTEM\RL_INVEST\new_verrsion_print.py:37: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[2] = 'NOT_INVEST'
c:\Users\Admin\Desktop\SYSTEM\RL_INVEST\new_verrsion_print.py:39: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[4:] = np.average(data_full.loc[id: , data_full.columns[4:]], axis=0)
c:\

TIME    PROFIT      SYMBOL EXCHANGE    MARKET_CAP  \
0       90  1.000000  NOT_INVEST     HOSE  8.873960e+12   
1       90  0.000000         AAA     HOSE  4.893114e+12   
2       90  0.000000         AAT     HOSE  8.485598e+11   
3       90  0.000000         ABS     HOSE  9.451310e+11   
4       90  0.000000         ACC     HOSE  1.911000e+12   
...    ...       ...         ...      ...           ...   
7119    29  0.829231         GIL     HOSE  2.957500e+11   
7120    29  0.792308         VSH     HOSE  8.125000e+12   
7121    29  0.741068         FPT     HOSE  2.961458e+13   
7122    29  0.724551         GMD     HOSE  7.643971e+12   
7123    29  0.676471         NAV     HOSE  4.250000e+11   

      Basic earnings per share  Other expenses  Financial expenses  \
0                231283.594397    8.469288e+09        5.072332e+10   
1                     0.000000    3.926632e+09        5.918750e+10   
2                  1384.000000    1.576288e+08        5.314787e+09   
3                     0.000000    6.931579e+08        1.141712e+10   
4                   258.000000    9.234700e+04        5.818817e+09   
...                        ...             ...                 ...   
7119                  0.000000    1.178573e+07        4.434805e+08   
7120                  0.000000    0.000000e+00        4.036377e+09   
7121               2550.000000    6.714888e+09        1.364417e+10   
7122                  0.000000    1.093278e+07        9.889580e+09   
7123                  0.000000    1.197081e+09        6.337996e+08   

         VolumeARG  Financial income  ...  Cash and cash equivalents  \
0     8.857091e+05      6.373902e+10  ...               6.778475e+11   
1     5.156710e+06      6.215189e+10  ...               1.018940e+12   
2     1.027330e+06      9.241194e+07  ...               3.328005e+10   
3     7.377700e+05      8.641370e+07  ...               2.160073e+10   
4     3.242300e+05      2.771447e+10  ...               7.737720e+11   
...            ...               ...  ...                        ...   
7119  2.435300e+04      1.918037e+08  ...               5.592835e+09   
7120  8.040500e+04      1.217429e+10  ...               1.117020e+11   
7121  1.016800e+05      1.010007e+10  ...               5.111802e+11   
7122  1.322200e+05      2.829137e+10  ...               1.335678e+12   
7123  8.241000e+03      7.865327e+08  ...               4.463200e+09   

      Short-term trade payables  \
0                  5.893811e+11   
1                  9.794080e+11   
2                  1.410469e+10   
3                  1.738495e+11   
4                  8.828534e+10   
...                         ...   
7119               2.042547e+10   
7120               7.003186e+09   
7121               4.444050e+11   
7122               0.000000e+00   
7123               1.103084e+10   

      Taxes and other obligations to the State Budget  Gross profit  \
0                                        1.097540e+11  3.105095e+11   
1                                        2.943622e+10  3.430300e+11   
2                                        2.253305e+10  1.191474e+11   
3                                        2.044294e+10  2.653042e+10   
4                                        8.608350e+09  1.338862e+10   
...                                               ...           ...   
7119                                     1.471138e+08  1.327977e+10   
7120                                     4.384513e+09  5.236953e+10   
7121                                     1.211761e+11  4.029315e+11   
7122                                     0.000000e+00  5.367310e+10   
7123                                     1.463231e+09  1.090782e+10   

      Other short-term payables  In which: Loan interest expenses  \
0                  4.307930e+11                      3.586968e+10   
1                  2.816613e+11                      3.589115e+10   
2                  2.649353e+06                      5.314787e+09   
3                  1.491120e+09          

In [5]:
result, per_file = normal_main(player_random1, 1,[0])
result, per_file

check khi gan:  [ 41  49  80  69  33  42  43  20  57  81 132  87 150 120  74  86  50  33
  45  38  93  39  34  53  49  49  70  72  74  70  93  80  79  86 106  90
 123 107 106  97 119 133 125 135 111 102  99 104 118 122 110 108 119 125
 134 164 188 166 224 196 209 168]
chon ct:  [-2.75047280e-11 -1.71101588e-10  1.19961567e-19  2.04365558e-17
  9.82899388e-17  9.88501022e-15  3.11712004e-18  8.38039397e-09
 -6.47878499e-07  8.55398037e-12] [1, [[2, 15, 8, 18, 14, 17, 11, 1, 23], [24, 0, 0, 0, 0, 0, 0, 0, 0]], 0, [[20, 14, 14, 6, 3, 12, 19, 23, 3], [25, 0, 0, 0, 0, 0, 0, 0, 0]], 1, [[17, 4, 25, 5, 2, 3, 24, 7, 21, 8, 15, 12, 8, 1], [22, 9, 9, 9, 23, 13, 0, 0, 0, 0, 0, 0, 0, 0]], 0, [[21, 19, 11, 9, 23, 12, 24, 12, 5, 17], [8, 6, 0, 0, 0, 0, 0, 0, 0, 0]], 0, [[8, 13, 25, 13, 8, 10, 14, 20], [0, 0, 0, 0, 0, 0, 0, 0]], 0, [[4, 7, 19, 20, 23, 7, 20, 6, 1, 3, 10], [14, 5, 13, 0, 0, 0, 0, 0, 0, 0, 0]]]
check khi gan:  [ 40  49  82  63  28  40  37  16  55  67 111  71 117  99  59  76  44  28
  4

(array([0., 1.]), [0])

In [13]:
print(gmean(A))


0.631898044572946


In [20]:
test1 = [0, [[19, 12, 10, 6, 7, 15, 13, 2, 17, 21, 14], [20, 1, 24, 4, 0, 0, 0, 0, 0, 0, 0]], 1, [[15, 6, 6, 18, 6, 11, 25, 15, 12, 10, 25, 13, 2, 24, 21, 2], [19, 9, 4, 22, 7, 7, 3, 5, 23, 0, 0, 0, 0, 0, 0, 0]], 0, [[6, 24, 4, 16, 2, 3, 2, 16, 9, 8, 16, 22], [21, 18, 10, 21, 18, 0, 0, 0, 0, 0, 0, 0]], 0, [[19, 1, 17, 18, 5, 9, 9, 20, 4, 14, 20, 5], [25, 3, 3, 10, 23, 0, 0, 0, 0, 0, 0, 0]]]



test2 =  [0, [[12, 6, 3], [7, 21, 0]]]

In [21]:




LIST_RANK_NOT_INVEST

array([ 18,  45,   8,   2,  10,   6,   4,  19,  68,  86,  16,  88,  25,
        16,  54,   9,  13,  25,  16,  48,   9,  10,  47,  22,  30,  40,
        81,  48,  55,  68,  29,  29,  67,  48,  37,  74,  92,  78,  50,
        73,  81,  44,  93,  75,  38,  53,  47,  70,  71,  74,  27,  39,
        88, 123, 124, 136, 102, 175, 102,  72,  56,   1], dtype=int64)

In [22]:
def test_ct(test):
    result_fomula = np.zeros(data_arr.shape[1])
    op = -1
    for item in test:
        if type(item) == int:
            if item == 0:
                op = 0
            else:
                op = 1
        else:
            result_temp = np.zeros(data_arr.shape[1])+1
            for id in range(len(item[0])):
                num = data_arr[item[0][id]]
                denom = data_arr[item[1][id]]
                denom_zero = np.where(denom == 0)[0]
                denom[denom_zero] = 1
                num[denom_zero] = 1
                result_temp =  result_temp*(num/denom)
            if op == 1:
                result_fomula = result_fomula + result_temp
            elif op == 0:
                result_fomula = result_fomula - result_temp
            else:
                raise Exception('toang cmnr')
            op = -1
    return result_fomula

test_ct1 = test_ct(test2)

In [10]:
test_ct1

array([-2.26622848e+01,  3.13509693e-02, -2.26636784e+01, ...,
       -5.58899903e-22,  6.12750329e-03,  9.17629342e-12])

In [11]:
temp = np.zeros(ALL_QUARTER)

In [12]:
index_test

array([   0,  203,  439,  665,  915, 1107, 1322, 1509, 1672, 1830, 1980,
       2118, 2252, 2398, 2537, 2660, 2784, 2902, 3029, 3188, 3331, 3485,
       3622, 3735, 3856, 3978, 4117, 4221, 4352, 4450, 4546, 4647, 4761,
       4855, 4947, 5045, 5138, 5202, 5268, 5342, 5391, 5448, 5566, 5617,
       5677, 5717, 5785, 5891, 5981, 6123, 6292, 6390, 6542, 6639, 6711,
       6732, 6780, 6831, 6869, 6940, 7029, 7081, 7124])

In [25]:
test_temp = test_ct1[index_test[0]:index_test[1]]
test_temp[:10]
np.argmax(test_temp)

21

In [26]:
np.max(test_temp)

315.98372860844694

In [19]:
test_temp

array([ 2.01994485e-27,  5.76516474e-09,  6.21337306e-02,  6.69152213e-15,
        1.14976623e+24,  4.07042748e-12,  6.62782623e-26, -5.09290673e-04,
       -2.41208120e+02,  3.84033835e+03,  2.19862291e-01,  4.33028290e-10,
       -6.29679564e-02, -8.10885432e+10,  3.09135241e+00,  3.84117112e-01,
        2.81144938e+00, -2.31520918e+01,  4.34129381e-14,  6.57688515e-07,
        1.11094644e-12, -7.14317280e-04,  5.57037425e+09,  5.66380046e+26,
        6.97268221e-30, -1.37605897e-08,  4.87291134e+12,  4.25927955e-02,
        1.33915848e-11,  4.49686047e-10, -3.46213909e-13,  1.94043085e-04,
        7.82801321e+00,  1.44983796e-41,  1.81487747e-03, -8.09625324e-06,
       -6.87656024e-44, -1.03658602e-09, -7.72597784e+15, -5.37837908e-30,
       -5.58899903e-22,  6.12750329e-03,  9.17629342e-12])

In [16]:
test_temp

array([ 2.01994485e-27,  5.76516474e-09,  6.21337306e-02,  6.69152213e-15,
        1.14976623e+24,  4.07042748e-12,  6.62782623e-26, -5.09290673e-04,
       -2.41208120e+02,  3.84033835e+03,  2.19862291e-01,  4.33028290e-10,
       -6.29679564e-02, -8.10885432e+10,  3.09135241e+00,  3.84117112e-01,
        2.81144938e+00, -2.31520918e+01,  4.34129381e-14,  6.57688515e-07,
        1.11094644e-12, -7.14317280e-04,  5.57037425e+09,  5.66380046e+26,
        6.97268221e-30, -1.37605897e-08,  4.87291134e+12,  4.25927955e-02,
        1.33915848e-11,  4.49686047e-10, -3.46213909e-13,  1.94043085e-04,
        7.82801321e+00,  1.44983796e-41,  1.81487747e-03, -8.09625324e-06,
       -6.87656024e-44, -1.03658602e-09, -7.72597784e+15, -5.37837908e-30,
       -5.58899903e-22,  6.12750329e-03,  9.17629342e-12])

In [9]:
index_rank = np.argsort(-test_temp)+1
index_rank

array([171,  16, 153,  93, 114,  95,  44, 189, 190, 145,  35, 106, 143,
       101, 105,  41, 140,  15,  52,  58,  46,  53, 149, 181, 173,  67,
       198,  42, 202,  11,   1,  45,  55, 148,  81,  22,  28,  56, 193,
        29, 119, 129, 108,  78, 137, 150,  71, 184, 135,  26, 186, 147,
        74, 126,  40,  82, 176,  49,  70,  19, 154,  92,  34, 132, 136,
       158, 177,  88, 164,  68, 128,  64, 118, 160,  98,  48,  57, 116,
        43,   9,  63,  69, 159,  87, 152,  75, 166,   6,  30,  50,  38,
       142, 199, 113,  36, 100, 141, 175,  37,  18,  17, 111,  99, 112,
       120,  13,  59,  90, 115, 124,  27, 156, 196, 168,  94, 187,  96,
         2,  20,  83,  80,  12, 192, 138,  60, 163, 161, 134,  73,  84,
       167,  47,  89,   7, 110, 133, 157, 172,  24, 122, 162,  21, 123,
         4, 144,  14,  97, 127,  33, 139, 194,  91, 107,  31,  39, 151,
        54,  72, 178,  86, 179, 183, 104,  25,  23, 185,  65, 117,  77,
       102, 201, 109, 169, 170, 146,  76, 130, 165, 200, 121,  8

In [28]:
index_rank[18]

45

In [14]:
data_full[data_full['TIME'] == 30].reset_index(drop=True)

TIME    PROFIT      SYMBOL EXCHANGE    MARKET_CAP  \
0     30  2.209184         LAF     HOSE  1.136585e+11   
1     30  2.152778         UNI     HOSE  1.080000e+11   
2     30  1.833180         TCT     HOSE  3.468745e+11   
3     30  1.791667         BMC     HOSE  1.227470e+12   
4     30  1.777778         MHC     HOSE  2.957187e+11   
5     30  1.747253         HTV     HOSE  2.184000e+11   
6     30  1.652174         IMP     HOSE  1.274948e+12   
7     30  1.547445         BBC     HOSE  6.960764e+11   
8     30  1.445783         PAC     HOSE  4.259145e+11   
9     30  1.433871         DMC     HOSE  1.707480e+12   
10    30  1.431193         NAV     HOSE  2.725000e+11   
11    30  1.392157         SMC     HOSE  3.824968e+11   
12    30  1.381579         DHA     HOSE  5.096940e+11   
13    30  1.377632         DHG     HOSE  3.040000e+12   
14    30  1.353659         BHS     HOSE  6.907568e+11   
15    30  1.333333         TAC     HOSE  2.220683e+12   
16    30  1.317343         KHA     HOSE  1.771698e+11   
17    30  1.303922         GMC     HOSE  1.160250e+11   
18    30  1.281996         VSH     HOSE  5.762500e+12   
19    30  1.274257         TTP     HOSE  1.076155e+12   
20    30  1.258475         BT6     HOSE  5.900000e+11   
21    30  1.257426         PPC     HOSE  1.569035e+13   
22    30  1.251445         KHP     HOSE  5.647447e+11   
23    30  1.247706         FPT     HOSE  1.988494e+13   
24    30  1.233333         GMD     HOSE  5.492674e+12   
25    30  1.233333         SSC     HOSE  6.000000e+11   
26    30  1.232179         PGC     HOSE  1.227335e+12   
27    30  1.200000         HAP     HOSE  4.860203e+11   
28    30  1.175214         GIL     HOSE  2.129400e+11   
29    30  1.156250         HRC     HOSE  2.761756e+12   
30    30  1.149701         TDH     HOSE  2.839000e+12   
31    30  1.137500         SJD     HOSE  1.040000e+12   
32    30  1.122881         SJS     HOSE  4.720000e+12   
33    30  1.114035         HBC     HOSE  6.365499e+11   
34    30  1.094382         GTA     HOSE  3.741449e+11   
35    30  1.087302         ITA     HOSE  7.560000e+12   
36    30  1.082353         VNM     HOSE  2.979686e+13   
37    30  1.078740         DRC     HOSE  1.655896e+12   
38    30  1.078613         HAS     HOSE  2.159671e+11   
39    30  1.077419         PVD     HOSE  1.201556e+13   
40    30  1.074419         BBT     HOSE  1.470600e+11   
41    30  1.061224         DCT     HOSE  3.556620e+11   
42    30  1.023529         BMP     HOSE  2.368678e+12   
43    30  1.000000         AGF     HOSE  1.234492e+12   
44    30  1.000000  NOT_INVEST     HOSE  3.915912e+12   
45    30  0.994500         NKD     HOSE  2.015956e+12   
46    30  0.990000         SFC     HOSE  1.700000e+11   
47    30  0.979710         CII     HOSE  2.070000e+12   
48    30  0.973239         VIP     HOSE  2.990520e+12   
49    30  0.961321         ABT     HOSE  6.677999e+11   
50    30  0.925974         KDC     HOSE  8.315923e+12   
51    30  0.815517         VID     HOSE  4.904306e+11   

    Basic earnings per share  Other expenses  Financial expenses  \
0                    0.00000    7.476612e+07        5.847806e+09   
1                    0.00000    0.000000e+00        6.887626e+07   
2                11680.00000    0.000000e+00        8.649829e+07   
3                    0.00000    0.000000e+00        0.000000e+00   
4                  493.00000    0.000000e+00        5.108305e+08   
5                  691.00000    0.000000e+00        3.113651e+07   
6                    0.00000    1.464202e+08        1.381090e+09   
7                    0.00000    3.001039e+08        5.385219e+08   
8                    0.00000    4.745189e+10        5.819879e+09   
9                    0.00000    1.686106e+09        2.874278e+09   
10                   0.00000    3.000000e+02        7.347913e+08   
11                   0.00000    3.195307e+06        4.547097e+09   
12                2012.00000    0.000000e+00        4.626000e+07   
13                   0.00000  

In [4]:
# result, per_file = normal_main(player_random1, 1000,[0])
result, per_file

(array([503., 497.]), [0])

In [ ]:
result, per_file = normal_main(player_random1,  1,[0])
result, per_file

In [3]:
LIST_RANK_NOT_INVEST_CT1


array([ 2,  2,  3,  3,  3,  3,  2,  2,  3,  2,  6,  6, 10, 10,  7,  8,  8,
        6,  5,  5,  9,  6,  7,  8,  9,  9,  9, 10,  9, 11, 12, 10,  9,  8,
       12, 12, 14, 13, 12, 15, 13, 16, 14, 18, 16, 15, 14, 14, 14, 12, 15,
        9, 12, 11, 11, 15, 17, 16, 17, 21, 19, 19], dtype=int64)

In [24]:
data_full.to_csv('Trang.csv', index=False)

In [4]:
LIST_RANK_NOT_INVEST_CT2

array([ 2,  2,  4,  2,  4,  3,  2,  1,  4,  2,  7,  4, 16, 10,  9, 10,  7,
        6,  2,  3,  9,  9,  9, 11, 14, 12, 16, 10, 14, 16, 19, 15, 16, 16,
       20, 16, 23, 15, 17, 17, 22, 26, 21, 23, 24, 20, 18, 17, 23, 23, 19,
       16, 22, 23, 26, 24, 45, 33, 39, 41, 38, 36], dtype=int64)

In [40]:
import pandas as pd
import math
import numpy as np
import heapq
from scipy.stats.mstats import gmean, hmean
import numba as nb
import random


data_full_load = pd.read_csv('data_test.csv')
data_full_load = data_full_load.sort_values(by=['TIME', 'PROFIT'], ascending=[False, False], ignore_index=True)
def get_index_T(data_full):
    list_T = data_full['TIME']
    index_T = [0]
    for i in range(len(list_T)-1):
        if list_T[i] != list_T[i+1]:
            index_T.append(i+1)
    index_T.append(len(list_T))
    return index_T  
index_test = get_index_T(data_full_load)
data_full = data_full_load.copy()
for id in index_test[:-1]:
    s = data_full_load.iloc[id]
    s[1] = 1
    s[2] = 'NOT_INVEST'
    # s[4:] = np.full(len(data_full.columns) - 4, 1)
    s[4:] = np.average(data_full.loc[id: , data_full.columns[4:]], axis=0)
    data_full = data_full.append(s)
data_full = data_full.sort_values(by=['TIME', 'PROFIT'], ascending=[False, False], ignore_index=True)
index_test = np.array(get_index_T(data_full))
data_arr = np.array(data_full[data_full.columns[4:]]).T
NUMBER_VARIABLE = len(data_arr)
all_fomula = np.array(pd.read_csv('congthuc.csv')['fomula'])
TOP_COMP_PER_QUARTER = 20
NUMBER_QUARTER_HISTORY = 24
ALL_QUARTER = len(np.unique(data_full['TIME']))

def get_variable(data_full):
    global A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z, PROFIT, COMPANY
    list_variable = [[]]*26
    list_column = list(data_full.columns)
    PROFIT = np.array(data_full["PROFIT"])
    COMPANY = np.array(data_full["SYMBOL"])
    for i in range(4, len(list_column)):
        list_variable[i-4] = np.array(data_full[list_column[i]])
    [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z] = list_variable

def save_data():
    np.save('index_test.npy', index_test)
    np.save('data.npy', data_arr)
    np.save('list_rank_profit_not_invest.npy', LIST_RANK_NOT_INVEST)
    np.save('list_company.npy', COMPANY)

get_variable(data_full)

def get_rank_not_invest():
    list_rank_ko_dau_tu = []
    for j in range(len(index_test)-1, 0, -1):
        # profit_q = PROFIT[index_test[j-1]:index_test[j]]
        COMP = COMPANY[index_test[j-1]:index_test[j]]
        list_rank_ko_dau_tu.append(np.where(COMP == 'NOT_INVEST')[0][0]+1)
    return np.array(list_rank_ko_dau_tu)

LIST_RANK_NOT_INVEST = get_rank_not_invest()
LIST_RANK_NOT_INVEST_TEMP = np.zeros(ALL_QUARTER)
LIST_RANK_CT1 = np.zeros(ALL_QUARTER)
LIST_RANK_NOT_INVEST_CT1 = np.zeros(ALL_QUARTER)
LIST_RANK_CT2 = np.zeros(ALL_QUARTER)
LIST_RANK_NOT_INVEST_CT2 = np.zeros(ALL_QUARTER)
LIST_PROFIT_CT1 = np.zeros(ALL_QUARTER)
LIST_PROFIT_CT2 = np.zeros(ALL_QUARTER)


def get_in4_rank_fomula(result_fomula):
    list_rank = []
    list_com = []
    for j in range(len(index_test)-1, 0, -1):
        COMP = COMPANY[index_test[j-1]:index_test[j]]
        rank_thuc = np.argsort(-result_fomula[index_test[j-1]:index_test[j]]) + 1
        list_rank.append(rank_thuc[0])
        list_com.append(COMP[rank_thuc[0]-1])
    return list_rank, list_com

#Hàm này tính cả list_profit
# def get_in4_fomula(fomula):
#     result_ =  np.nan_to_num(eval(fomula), nan=-math.inf, posinf=-math.inf, neginf=-math.inf)
#     list_top_comp = []
#     list_profit = []
#     for j in range(len(index_test)-1, 0, -1):
#         rank_thuc = np.argsort(-result_[index_test[j-1]:index_test[j]]) + 1
#         list_profit.append(PROFIT[index_test[j-1]:index_test[j]][rank_thuc[0]-1])
#         list_top_comp.append(rank_thuc[:TOP_COMP_PER_QUARTER])
#     return np.array(list_top_comp).flatten(), np.array(list_profit)

@nb.njit()
def get_in4_fomula(result_fomula, list_rank_not_invest_temp):
    global LIST_RANK_NOT_INVEST, index_test
    # result_ =  np.nan_to_num(eval(fomula), nan=-math.inf, posinf=-math.inf, neginf=-math.inf)
    list_top_comp = np.array([-1])
    list_rank_not_invest_ct = np.array([-1])
    
    for j in range(len(index_test)-1, 0, -1):
        top2 = heapq.nlargest(2,result_fomula[index_test[j-1]:index_test[j]])         #lấy top 2 giá trị lớn nhất
        if top2[0] == top2[1] or np.max(result_fomula[index_test[j-1]:index_test[j]]) == np.min(result_fomula[index_test[j-1]:index_test[j]]):
            # print('toang cong thuc', top2, np.max(result_fomula[index_test[j-1]:index_test[j]]), np.min(result_fomula[index_test[j-1]:index_test[j]]))
            return np.array([-1]), np.array([-1]), 0
        rank_thuc = np.argsort(-result_fomula[index_test[j-1]:index_test[j]]) + 1
        id_not_invest = LIST_RANK_NOT_INVEST[-j] 
        if list_rank_not_invest_ct[0] == -1:
            list_rank_not_invest_ct = np.array([np.where(rank_thuc == id_not_invest)[0][0]+1])
            list_top_comp = rank_thuc[:TOP_COMP_PER_QUARTER]
        else:
            list_rank_not_invest_ct = np.append(list_rank_not_invest_ct, np.where(rank_thuc == id_not_invest)[0][0]+1)
            list_top_comp = np.append(list_top_comp, rank_thuc[:TOP_COMP_PER_QUARTER])
    list_rank_not_invest_temp = list_rank_not_invest_ct
    return list_top_comp, list_rank_not_invest_temp, 1
    # return np.array(list_top_comp).flatten(), 1

IN4_CT1_INDEX = 0
IN4_CT2_INDEX = ALL_QUARTER*TOP_COMP_PER_QUARTER
HISTORY_AGENT_INDEX= IN4_CT2_INDEX + ALL_QUARTER*TOP_COMP_PER_QUARTER
HISTORY_SYS_BOT_INDEX = HISTORY_AGENT_INDEX + ALL_QUARTER
HISTORY_PROFIT_AGENT = HISTORY_SYS_BOT_INDEX + ALL_QUARTER
ID_NOT_INVEST_CT1 = HISTORY_PROFIT_AGENT + ALL_QUARTER
ID_NOT_INVEST_CT2 = ID_NOT_INVEST_CT1 + 1
CURRENT_QUARTER_INDEX = ID_NOT_INVEST_CT2 + 1
ID_ACTION_INDEX = CURRENT_QUARTER_INDEX + 1
CHECK_END_INDEX = ID_ACTION_INDEX + 1

P_IN4_CT1 = 0
P_IN4_CT2 = P_IN4_CT1 + TOP_COMP_PER_QUARTER*NUMBER_QUARTER_HISTORY
P_GMEAN_P1 = P_IN4_CT2 + TOP_COMP_PER_QUARTER*NUMBER_QUARTER_HISTORY
P_GMEAN_P2 = P_GMEAN_P1 + 1
P_ID_NOT_INVEST_CT1 = P_GMEAN_P2 + 1
P_ID_NOT_INVEST_CT2 = P_ID_NOT_INVEST_CT1 + 1

save_data()

def reset():
    global LIST_RANK_CT1, LIST_RANK_CT2, LIST_PROFIT_CT1, LIST_PROFIT_CT2, LIST_RANK_NOT_INVEST_CT1, LIST_RANK_NOT_INVEST_CT2, LIST_RANK_NOT_INVEST_TEMP
    '''
    Hàm này trả ra 2 công thức và list top20 comp qua từng quý của công thức và các thông tin cần thiết khác
    '''
    # list_fomula = []
    count_fomula = 0
    while count_fomula < 2:
        result_fomula = create_fomula(data_arr)
        temp, LIST_RANK_NOT_INVEST_TEMP, check = get_in4_fomula(result_fomula, LIST_RANK_NOT_INVEST_TEMP)
        # print('check getin4', len(temp), check, result_fomula[:10], temp[:10])
        # print('TEMP, ', LIST_RANK_NOT_INVEST_TEMP[:10])
        count_fomula += check
        if count_fomula == 1 and check == 1:
            LIST_RANK_CT1 = temp.copy()
            LIST_RANK_NOT_INVEST_CT1 = LIST_RANK_NOT_INVEST_TEMP.copy()
            # list_fomula.append(fomula)
        elif count_fomula == 2 and check == 1:
            LIST_RANK_CT2 = temp.copy()
            LIST_RANK_NOT_INVEST_CT2 = LIST_RANK_NOT_INVEST_TEMP.copy()
            # list_fomula.append(fomula)
    id_not_invest_ct1 = LIST_RANK_NOT_INVEST_CT1[0]
    id_not_invest_ct2 = LIST_RANK_NOT_INVEST_CT2[0]
    current_quarter = 0
    id_action = 0
    check_end_game = 0
    history_agent = np.zeros(ALL_QUARTER*3)
    # LIST_RANK_CT1, LIST_PROFIT_CT1 = get_in4_fomula(list_fomula[0])
    # LIST_RANK_CT2, LIST_PROFIT_CT2 = get_in4_fomula(list_fomula[1])
    env_state = np.concatenate((LIST_RANK_CT1, LIST_RANK_CT2, history_agent, np.array([id_not_invest_ct1, id_not_invest_ct2, current_quarter, id_action, check_end_game])))
    return env_state

@nb.njit
def state_to_player(env_state):
    '''
    Hàm này trả ra lịch sử kết quả của 2 công thức trong các quý trước đó
    '''
    id_action = env_state[ID_ACTION_INDEX]
    player_state = np.zeros(2*NUMBER_QUARTER_HISTORY*TOP_COMP_PER_QUARTER + 4)
    player_state[P_ID_NOT_INVEST_CT1] = env_state[ID_NOT_INVEST_CT1]
    player_state[P_ID_NOT_INVEST_CT2] = env_state[ID_NOT_INVEST_CT2]
    if env_state[CURRENT_QUARTER_INDEX] != 0:
        history_ct1 = env_state[max(IN4_CT1_INDEX, TOP_COMP_PER_QUARTER*(env_state[CURRENT_QUARTER_INDEX]-24)):int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER)]
        history_ct2 = env_state[max(IN4_CT2_INDEX, TOP_COMP_PER_QUARTER*(env_state[CURRENT_QUARTER_INDEX]-24)+IN4_CT2_INDEX):int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER)+IN4_CT2_INDEX]
        player_state[P_IN4_CT1:P_IN4_CT1+len(history_ct1)] = history_ct1
        player_state[P_IN4_CT2:P_IN4_CT2+len(history_ct2)] = history_ct2
    agent_history = env_state[HISTORY_AGENT_INDEX : HISTORY_AGENT_INDEX+ALL_QUARTER][:int(env_state[CURRENT_QUARTER_INDEX])]
    sys_bot_history = env_state[HISTORY_SYS_BOT_INDEX : HISTORY_SYS_BOT_INDEX+ALL_QUARTER][:int(env_state[CURRENT_QUARTER_INDEX])]
    if env_state[CHECK_END_INDEX] == 1:
        if id_action == 0:
            player_state[P_GMEAN_P1] = np.exp(np.mean(np.log(agent_history)))
            player_state[P_GMEAN_P2] = np.exp(np.mean(np.log(sys_bot_history)))
        else:
            player_state[P_GMEAN_P1] = np.exp(np.mean(np.log(sys_bot_history)))
            player_state[P_GMEAN_P2] = np.exp(np.mean(np.log(agent_history)))
    return player_state

@nb.njit
def step(action, env_state):
    global LIST_RANK_CT1, LIST_RANK_CT2, LIST_PROFIT_CT1, LIST_PROFIT_CT2, LIST_RANK_NOT_INVEST_CT1, LIST_RANK_NOT_INVEST_CT2
    id_action = env_state[ID_ACTION_INDEX]
    result_quarter = 0
    if action == 0:
        result_quarter = LIST_RANK_NOT_INVEST[int(env_state[CURRENT_QUARTER_INDEX])]
        # env_state[int(HISTORY_PROFIT_AGENT+env_state[CURRENT_QUARTER_INDEX])] = 1
    elif action == 1:
        result_quarter = env_state[int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER)]
        # env_state[int(HISTORY_PROFIT_AGENT+env_state[CURRENT_QUARTER_INDEX])] = LIST_PROFIT_CT1[int(env_state[CURRENT_QUARTER_INDEX])]
    else:
        result_quarter = env_state[int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER+IN4_CT2_INDEX)]
        # env_state[int(HISTORY_PROFIT_AGENT+env_state[CURRENT_QUARTER_INDEX])] = LIST_PROFIT_CT2[int(env_state[CURRENT_QUARTER_INDEX])]
    if result_quarter == 0:
        # print('toang',action,  env_state[int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER+IN4_CT2_INDEX)], np.min(LIST_RANK_CT2))
        raise Exception('toang action')
    rank_3_action = np.array([LIST_RANK_NOT_INVEST[int(env_state[CURRENT_QUARTER_INDEX])], env_state[int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER)], env_state[int(env_state[CURRENT_QUARTER_INDEX]*TOP_COMP_PER_QUARTER+IN4_CT2_INDEX)]])
    rank_3_action = np.sort(rank_3_action)
    top_action = np.where(rank_3_action == result_quarter)[0][0] + 1
    # print('quarter', int(env_state[CURRENT_QUARTER_INDEX]),'check', 1/top_action, 'action', action, 'topaction',rank_3_action)
    env_state[int(HISTORY_AGENT_INDEX + ALL_QUARTER*id_action +env_state[CURRENT_QUARTER_INDEX])] = (4-top_action)/3
    if env_state[ID_ACTION_INDEX] == 1:
        env_state[CURRENT_QUARTER_INDEX] += 1  
        #rank giá trị công thức của việc không đầu tư
        if env_state[CURRENT_QUARTER_INDEX] < ALL_QUARTER:
            env_state[ID_NOT_INVEST_CT1] = LIST_RANK_NOT_INVEST_CT1[int(env_state[CURRENT_QUARTER_INDEX])]
            env_state[ID_NOT_INVEST_CT2] = LIST_RANK_NOT_INVEST_CT2[int(env_state[CURRENT_QUARTER_INDEX])]
        env_state[ID_ACTION_INDEX] = 0
    else:
        env_state[ID_ACTION_INDEX] = 1

    return env_state

def action_player(env_state, list_player, temp_file, per_file):
    player_state = state_to_player(env_state)
    current_player = int(env_state[ID_ACTION_INDEX])
    played_move,temp_file,per_file = list_player[current_player](player_state, temp_file, per_file)
    return played_move,temp_file, per_file
    
@nb.njit
def check_winner(env_state):
    agent_history = env_state[HISTORY_AGENT_INDEX : HISTORY_AGENT_INDEX+ALL_QUARTER]
    sys_bot_history = env_state[HISTORY_SYS_BOT_INDEX : HISTORY_SYS_BOT_INDEX+ALL_QUARTER]
    np.exp(np.mean(np.log(sys_bot_history)))
    if np.exp(np.mean(np.log(agent_history))) > np.exp(np.mean(np.log(sys_bot_history))): return 0
    else: return 1

@nb.njit
def check_victory(player_state):
    if not (player_state[P_GMEAN_P1] == player_state[P_GMEAN_P2] and player_state[P_GMEAN_P2] == 0):
        if player_state[P_GMEAN_P1] > player_state[P_GMEAN_P2]: return 1
        else: return 0
    else: return -1

@nb.njit()
def create_fomula(data_arr):
    power = np.random.randint(1, 10)
    operand = np.random.randint(1, 10)
    result_fomula = np.zeros(data_arr.shape[1])
    # ct = []
    for i in range(operand):
        op = np.random.randint(2)
        # ct.append(op)
        numerator = np.random.randint(power, NUMBER_VARIABLE - 1 - power)
        denominator = numerator - power
        numer_var = np.random.randint(1, NUMBER_VARIABLE, numerator)
        result_temp = np.zeros(data_arr.shape[1])+1
        if denominator > 0:
            all_var = np.arange(1,NUMBER_VARIABLE)
            for id in range(len(all_var)):
                if all_var[id] in numer_var:
                    all_var[id] = 0
            all_denom_var = all_var[all_var > 0]
            if len(all_denom_var) < denominator:
                all_denom_var = np.append(all_denom_var, np.random.choice(all_var, denominator - len(all_denom_var)))
            denom_var = np.random.choice(all_denom_var, denominator)
            denom_var = np.append(denom_var, np.zeros(numerator-denominator).astype(np.int64))
            denom_var = denom_var.astype(np.int64)
            # ct.append([numer_var, denom_var])
            for idx in range(len(numer_var)):
                num = data_arr[numer_var[idx]]
                denom = data_arr[denom_var[idx]]
                denom_zero = np.where(denom == 0)[0]
                denom[denom_zero] = 1
                num[denom_zero] = 1
                result_temp =  result_temp*(num/denom)
        else:
            denom_var = np.zeros(numerator).astype(np.int64)
            # ct.append([numer_var, denom_var])
            for id in range(len(numer_var)):
                num = data_arr[numer_var[id]]
                denom = data_arr[denom_var[id]]
                denom_zero = np.where(denom == 0)[0]
                denom[denom_zero] = 1
                num[denom_zero] = 1
                result_temp =  result_temp*(num/denom)
        if op == 1:
            result_fomula = result_fomula + result_temp
        else:
            result_fomula = result_fomula - result_temp
    return result_fomula

def create_fomula_old():
    all_char = ['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
    all_char = 'BCDEFGHIJKLMNOPQRSTUVWXYZ'
    power = np.random.randint(1, 10)
    # print('bậc: ', power)
    operand = np.random.randint(1, 10)
    # print('số toán hạng: ', operand)
    list_exp_child = []
    ct = '('
    for i in range(operand):
        ct += random.choice('+-')
        numerator = random.randint(power, 25-power)
        denominator = numerator - power
        numer_char = random.choices(all_char, k = numerator)
        ct += '(' + '*'.join(numer_char) + ')'
        # print(ct, 'mẫu', denominator)
        if denominator > 0:
            all_denom_char = list(set(numer_char)^set(all_char))
            # print('CHECK: ', len(all_denom_char) , denominator)
            if len(all_denom_char) < denominator:
                all_denom_char += random.choices(all_char, k = (denominator - len(all_denom_char)))
            denom_char = random.choices(all_denom_char, k = denominator)
            ct += '/(' + '*'.join(numer_char) + ')'
    ct += ')' + '/A'*power
    return ct

def one_game(list_player, temp_file, per_file):
    env_state = reset()
    count_turn = 0
    while count_turn < ALL_QUARTER*2:
        action, temp_file, per_file = action_player(env_state, list_player, temp_file, per_file)
        env_state = step(action, env_state)
        count_turn += 1
    env_state[CHECK_END_INDEX] = 1
    for id_player in range(len(list_player)):
        action, temp_file, per_file = action_player(env_state,list_player,temp_file, per_file)
        env_state[ID_ACTION_INDEX] = (env_state[ID_ACTION_INDEX] + 1)%len(list_player)
    result = check_winner(env_state)
    return result, per_file

def normal_main(agent_player, times, per_file):
    global data_full, data_arr
    count = np.zeros(2)
    # all_id_fomula = np.arange(len(all_fomula))
    list_player = [agent_player, player_random]
    for van in range(times):
        temp_file = [[0],[0]]
        # shuffle = np.random.choice(all_id_fomula, 2, replace=False)
        # list_fomula = all_fomula[shuffle]
        winner, file_per = one_game(list_player, temp_file, per_file)
        if winner == 0:
            count[0] += 1
        else:
            count[1] += 1
    return count, file_per

def player_random1(player_state, temp_file, per_file):
    list_action = np.array([0,1,2])
    action = int(np.random.choice(list_action))
    # print('check: ', player_state[P_ID_NOT_INVEST_CT1], player_state[P_ID_NOT_INVEST_CT2])
    check = check_victory(player_state)
    return action, temp_file, per_file

def player_random(player_state, temp_file, per_file):
    list_action = np.array([0,1,2])
    action = int(np.random.choice(list_action))
    # check = check_victory(player_state)
    return action, temp_file, per_file




C:\Users\Admin\AppData\Local\Temp\ipykernel_17996\3948151812.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[1] = 1
C:\Users\Admin\AppData\Local\Temp\ipykernel_17996\3948151812.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[2] = 'NOT_INVEST'
C:\Users\Admin\AppData\Local\Temp\ipykernel_17996\3948151812.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[4:] = np.average(data_full.loc[id: , data_full.columns[4:]], axis=

In [42]:
result, per_file = normal_main(player_random1, 1000,[0])
result, per_file

(array([523., 477.]), [0])

In [35]:
# LIST_RANK_NOT_INVEST = get_rank_not_invest()
# LIST_RANK_NOT_INVEST_TEMP = np.zeros(ALL_QUARTER)
# LIST_RANK_CT1 = np.zeros(ALL_QUARTER)
# LIST_RANK_NOT_INVEST_CT1 = np.zeros(ALL_QUARTER)
# LIST_RANK_CT2 = np.zeros(ALL_QUARTER)
# LIST_RANK_NOT_INVEST_CT2 = np.zeros(ALL_QUARTER)
# LIST_PROFIT_CT1 = np.zeros(ALL_QUARTER)
# LIST_PROFIT_CT2 = np.zeros(ALL_QUARTER)
LIST_RANK_NOT_INVEST_CT2

array([ 9,  6, 12,  7,  9, 17, 16,  3, 23, 28, 37, 20, 45, 43, 29, 32, 25,
       10, 21, 17, 36, 20, 19, 26, 25, 28, 32, 31, 27, 36, 32, 35, 31, 35,
       41, 36, 44, 37, 37, 43, 38, 51, 41, 50, 34, 42, 40, 45, 41, 52, 59,
       50, 46, 58, 62, 56, 48, 58, 47, 58, 49, 62], dtype=int64)

In [16]:
data_full[data_full['TIME'] == 29].reset_index(drop= True)

TIME    PROFIT      SYMBOL EXCHANGE    MARKET_CAP  \
0     29  1.711111         BMC     HOSE  7.081560e+11   
1     29  1.519455         DHG     HOSE  2.056000e+12   
2     29  1.493684         DMC     HOSE  1.118150e+12   
3     29  1.442029         NKD     HOSE  1.159200e+12   
4     29  1.352381         IMP     HOSE  8.820000e+11   
5     29  1.320312         HAP     HOSE  3.840161e+11   
6     29  1.300578         KDC     HOSE  5.189997e+12   
7     29  1.236364         BBC     HOSE  4.944500e+11   
8     29  1.202614         HAS     HOSE  1.909998e+11   
9     29  1.200000         ABT     HOSE  3.366000e+11   
10    29  1.175281         TTP     HOSE  9.482950e+11   
11    29  1.120567         DHA     HOSE  4.728082e+11   
12    29  1.098214         KHA     HOSE  2.196644e+11   
13    29  1.081633         SMC     HOSE  2.940000e+11   
14    29  1.043103         VID     HOSE  4.904306e+11   
15    29  1.040000         SJD     HOSE  1.040000e+12   
16    29  1.017857         AGF     HOSE  8.834087e+11   
17    29  1.000000  NOT_INVEST     HOSE  4.399968e+12   
18    29  0.998291         KHP     HOSE  6.365619e+11   
19    29  0.981481         NSC     HOSE  1.620000e+11   
20    29  0.971831         CII     HOSE  2.130000e+12   
21    29  0.970588         TYA     HOSE  2.053272e+11   
22    29  0.962500         DCT     HOSE  3.871151e+11   
23    29  0.962222         BHS     HOSE  7.290000e+11   
24    29  0.954887         ITA     HOSE  7.980000e+12   
25    29  0.951596         VNM     HOSE  3.295183e+13   
26    29  0.950820         BMP     HOSE  2.549812e+12   
27    29  0.946429         PGC     HOSE  1.119812e+12   
28    29  0.941449         TCR     HOSE  1.714305e+11   
29    29  0.941176         IFS     HOSE  2.435026e+11   
30    29  0.938202         HRC     HOSE  1.708800e+12   
31    29  0.926829         VIP     HOSE  3.453840e+12   
32    29  0.901515         DRC     HOSE  1.220670e+12   
33    29  0.894097         SJS     HOSE  5.760000e+12   
34    29  0.869744         SSC     HOSE  7.020000e+11   
35    29  0.865979         TDH     HOSE  3.298000e+12   
36    29  0.855000         PVD     HOSE  1.468800e+13   
37    29  0.838433         PPC     HOSE  2.081690e+13   
38    29  0.829231         GIL     HOSE  2.957500e+11   
39    29  0.792308         VSH     HOSE  8.125000e+12   
40    29  0.741068         FPT     HOSE  2.961458e+13   
41    29  0.724551         GMD     HOSE  7.643971e+12   
42    29  0.676471         NAV     HOSE  4.250000e+11   

    Basic earnings per share  Other expenses  Financial expenses  \
0                   0.000000    0.000000e+00        0.000000e+00   
1                3651.000000    2.089633e+08        5.538020e+09   
2                 911.000000    0.000000e+00        2.099700e+09   
3                   0.000000    1.122653e+07        2.207868e+09   
4                   0.000000    6.285308e+07        3.246889e+08   
5                   0.000000    2.037698e+09        6.690929e+08   
6                   0.000000    1.522705e+09        6.770757e+09   
7                   0.000000    1.816363e+07        1.986796e+08   
8                   0.000000    1.312103e+07        1.918014e+08   
9                   0.000000    9.559947e+08        6.258958e+08   
10                  0.000000    0.000000e+00        1.481058e+09   
11                  0.000000    0.000000e+00        1.118872e+08   
12                  0.000000    1.106717e+09        6.410808e+08   
13               1366.000000    6.060800e+04        3.828539e+09   
14                  0.000000    4.590573e+08        1.721893e+09   
15                  0.000000    4.755784e+07        1.463419e+10   
16                  0.000000    7.889334e+08        3.791295e+09   
17               2838.232435    3.066980e+09        1.924202e+10   
18                  0.000000    3.098661e+07        1.293322e+09   
19                  0.000000    0.000000e+00        0.000000e+00   
20                710.000000    7.206046e+07        8.765002e+09   

In [7]:
import numba as nb
import numpy as np

TEST = np.array([1,2,3])
TEST2 = np.arange(3)
print(TEST, TEST2)

@nb.njit()
def test(test):
    # global TEST, TEST2
    a = np.arange(5)
    test = np.append(test, 2)
    return a, test
x, y = test(TEST)
print(x)
print(TEST)

[1 2 3] [0 1 2]
[0 1 2 3 4]
[1 2 3]


In [4]:
TEST2

array([0, 1, 2])

In [6]:
a = np.array(['abc', 'CDF', 'EFG'])
np.save('test.npy', a )

In [7]:
with open('test.npy', 'rb') as f:
    b = np.load(f)
b 

array(['abc', 'CDF', 'EFG'], dtype='<U3')